<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

	<style>
		#main-div {margin-top: 50px;}
		.linkcls {margin-top: 15px;}
	</style>
    <title>Registration App</title>
  </head>
  <body>

<div class="container" id="main-div">
  <form>
    <h2>Registration App</h2>
    <div class="container">
      <div class="row">
        <a href="addRegistration" class="linkcls">Add Registration</a>
      </div>
      <div class="row" id="row2-div">
        <a href="listRegistrations" class="linkcls">List Registrations</a>
      </div>
      <div class="row" id="row3-div">
        <a href="jsonRegistrations" class="linkcls">JSON Registrations</a>
      </div>
      <div class="row" id="row3-div">
        <a href="jsonVehicles" class="linkcls">JSON Vehicles</a>
      </div>
      <div class="row" id="row3-div">
        <a href="jsonInsurers" class="linkcls">JSON Insurers</a>
      </div>
    </div>  
  </form>
</div>

</body>
</html>